import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ORIGIN="https://fitnest.reflectace.workers.dev";
const CONSENT_VERSION="3.7-health-signals";
const H={"Content-Type":"application/json","Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function res(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H})}
function admin(){const m=Deno.env.get("SUPABASE_SECRET_KEYS"),key=m?JSON.parse(m).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!key)throw new Error("server_key_missing");return createClient(Deno.env.get("SUPABASE_URL")!,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function avg(values:number[]){return values.length?values.reduce((sum,value)=>sum+value,0)/values.length:null}
function daysAgo(n:number){return new Date(Date.now()-n*86400000).toISOString().slice(0,10)}
function number(value:unknown){const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}

function rules(ctx:any){
  const weights=(ctx.weights||[]).slice().reverse(),workouts=ctx.workouts||[],checkins=ctx.checkins||[],profile=ctx.profile||{};
  const rpes=workouts.map((item:any)=>number(item.perceived_effort)).filter((value:number|null):value is number=>value!==null&&value>0),sleep=checkins.map((item:any)=>number(item.sleep_hours)).filter((value:number|null):value is number=>value!==null&&value>0),energy=checkins.map((item:any)=>number(item.energy)).filter((value:number|null):value is number=>value!==null&&value>0),steps=checkins.map((item:any)=>number(item.steps)).filter((value:number|null):value is number=>value!==null&&value>0),water=checkins.map((item:any)=>number(item.water_l)).filter((value:number|null):value is number=>value!==null&&value>0);
  const avgRpe=avg(rpes),avgSleep=avg(sleep),avgEnergy=avg(energy),avgSteps=avg(steps),avgWater=avg(water),lowSleepDays=sleep.filter(value=>value<6).length,lowEnergyDays=energy.filter(value=>value<=2).length,healthDays=new Set(checkins.map((item:any)=>item.checkin_date)).size,signalCount=[sleep.length,energy.length,steps.length,rpes.length].filter(Boolean).length;
  let weightPerWeek:null|number=null;if(weights.length>1){const first=weights[0],last=weights.at(-1),days=Math.max(1,(new Date(last.measured_on).getTime()-new Date(first.measured_on).getTime())/86400000);weightPerWeek=Number(((Number(last.weight_kg)-Number(first.weight_kg))/days*7).toFixed(2));}
  const stepGoal=number(profile.step_goal),waterGoal=number(profile.water_goal_l),stepsRatio=avgSteps&&stepGoal?avgSteps/stepGoal:null,waterRatio=avgWater&&waterGoal?avgWater/waterGoal:null;
  let level="unknown",status="Mehr Daten sammeln",summary="Mit einigen Tageswerten kann der Coach deine Belastung und Erholung besser einordnen.";const actions:string[]=[];
  if(weightPerWeek!==null&&weightPerWeek < -1){level="attention";status="Gewichtstrend prüfen";summary="Der aktuelle Gewichtstrend ist schneller als der sichere Orientierungswert von einem Kilogramm pro Woche.";actions.push("Den Gewichtsverlust nicht weiter beschleunigen und das Kalorienziel nicht automatisch senken.")}
  else if((sleep.length>=2&&avgSleep!==null&&avgSleep<6)||lowSleepDays>=2||(energy.length>=2&&avgEnergy!==null&&avgEnergy<2.5)||lowEnergyDays>=2||(rpes.length>=2&&avgRpe!==null&&avgRpe>=8.5)){level="low";status="Erholung priorisieren";summary="Mehrere Signale sprechen für einen vorsichtigeren Trainingstag. Dein Plan bleibt trotzdem vollständig verfügbar.";actions.push("Wenn du dich müde fühlst, wähle heute eine kürzere oder leichtere Einheit.")}
  else if((sleep.length>=2&&avgSleep!==null&&avgSleep<7)||(energy.length>=2&&avgEnergy!==null&&avgEnergy<3.5)||(rpes.length>=2&&avgRpe!==null&&avgRpe>=7.5)){level="moderate";status="Kontrolliert planen";summary="Einige Signale sind noch nicht vollständig erholt. Passe die Intensität an deine Tagesform an.";actions.push("Starte kontrolliert und entscheide nach dem Aufwärmen über die Intensität.")}
  else if(healthDays>=3&&signalCount>=2){level="stable";status="Stabile Signale";summary="Die verfügbaren Schlaf-, Energie- und Belastungswerte wirken insgesamt stabil.";actions.push("Der geplante Trainingsrhythmus passt. Eine kleine Steigerung bleibt optional.")}
  else actions.push("Schlaf und Energie an mehreren Tagen erfassen, um die Empfehlung zu verbessern.");
  if(stepsRatio!==null&&stepsRatio<.75)actions.push("Ein kurzer Spaziergang kann dein Schrittziel unterstützen. Er ist keine Pflicht für den Trainingstag.");if(waterRatio!==null&&waterRatio<.7)actions.push("Deine Flüssigkeitsmenge liegt unter deinem Ziel. Trinke über den Tag verteilt nach Durst.");actions.push("Alle Trainings- und KI-Planfunktionen bleiben verfügbar. Diese Auswertung ist nur ein Hinweis.");
  const confidence=healthDays>=5&&signalCount>=3?"hoch":healthDays>=3&&signalCount>=2?"mittel":"niedrig";
  return{level,status,summary,advisory:"Hinweis, keine Sperre",blocking:false,actions:[...new Set(actions)].slice(0,4),confidence,metrics:{healthDays,avgSleep:avgSleep===null?null:Number(avgSleep.toFixed(1)),lowSleepDays,avgEnergy:avgEnergy===null?null:Number(avgEnergy.toFixed(1)),lowEnergyDays,avgSteps:avgSteps===null?null:Math.round(avgSteps),avgWater:avgWater===null?null:Number(avgWater.toFixed(1)),workouts7:workouts.length,avgRpe:avgRpe===null?null:Number(avgRpe.toFixed(1)),weightPerWeek},signals:[{label:"Schlaf",value:avgSleep===null?"Noch keine Daten":`${avgSleep.toFixed(1)} Stunden im Mittel`,tone:avgSleep!==null&&avgSleep<6?"low":avgSleep!==null&&avgSleep<7?"moderate":"stable"},{label:"Energie",value:avgEnergy===null?"Noch keine Daten":`${avgEnergy.toFixed(1)} von 5 im Mittel`,tone:avgEnergy!==null&&avgEnergy<2.5?"low":avgEnergy!==null&&avgEnergy<3.5?"moderate":"stable"},{label:"Trainingslast",value:avgRpe===null?"Noch keine RPE Daten":`RPE ${avgRpe.toFixed(1)} im Mittel`,tone:avgRpe!==null&&avgRpe>=8.5?"low":avgRpe!==null&&avgRpe>=7.5?"moderate":"stable"},{label:"Schritte",value:avgSteps===null?"Noch keine Daten":`${Math.round(avgSteps).toLocaleString("de-DE")} im Mittel`,tone:stepsRatio!==null&&stepsRatio<.75?"moderate":"stable"}]};
}

async function context(db:any,userId:string){const [profile,goal,weights,workouts,checkins,nutrition,review]=await Promise.all([db.from("profiles").select("age,height_cm,activity_level,training_days,session_minutes,step_goal,water_goal_l").eq("user_id",userId).maybeSingle(),db.from("goals").select("start_weight_kg,target_weight_kg,target_date,status").eq("user_id",userId).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle(),db.from("body_metrics").select("measured_on,weight_kg").eq("user_id",userId).gte("measured_on",daysAgo(30)).order("measured_on",{ascending:false}),db.from("workout_sessions").select("planned_date,duration_minutes,perceived_effort,workout_type").eq("user_id",userId).eq("completed",true).gte("planned_date",daysAgo(7)).order("planned_date",{ascending:false}),db.from("daily_checkins").select("checkin_date,steps,water_l,sleep_hours,energy").eq("user_id",userId).gte("checkin_date",daysAgo(7)).order("checkin_date",{ascending:false}),db.from("nutrition_profiles").select("calories,protein_g,eating_pattern").eq("user_id",userId).eq("is_active",true).maybeSingle(),db.from("weekly_reviews").select("metrics,recommendation,status,week_start").eq("user_id",userId).order("week_start",{ascending:false}).limit(1).maybeSingle()]);for(const result of [profile,goal,weights,workouts,checkins,nutrition,review])if(result.error)throw result.error;return{profile:profile.data,goal:goal.data,weights:weights.data||[],workouts:workouts.data||[],checkins:checkins.data||[],nutrition:nutrition.data,weeklyReview:review.data}}
function extractText(json:any){return json?.output?.flatMap((item:any)=>item?.content||[]).find((item:any)=>item?.type==="output_text")?.text||""}
function cleanJson(text:string){return JSON.parse(text.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim())}
function safeInsight(candidate:any,fallback:any){const aiActions=Array.isArray(candidate?.actions)?candidate.actions.filter((item:any)=>typeof item==="string").slice(0,3):fallback.actions.slice(0,3);return{...fallback,...candidate,level:["unknown","stable","moderate","low","attention"].includes(candidate?.level)?candidate.level:fallback.level,status:String(candidate?.status||fallback.status).slice(0,90),summary:String(candidate?.summary||fallback.summary).slice(0,320),advisory:"Hinweis, keine Sperre",blocking:false,actions:[...aiActions,"Alle Trainings- und KI-Planfunktionen bleiben verfügbar. Diese Auswertung ist nur ein Hinweis."],metrics:{...fallback.metrics,...(candidate?.metrics||{})},signals:fallback.signals,confidence:fallback.confidence}}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return res({ok:false,code:"method_not_allowed"},405);
  try{
    const body=await req.json().catch(()=>({}));if(body.consent!==true||body.consentVersion!==CONSENT_VERSION)return res({ok:false,code:"consent_required",message:"Für Coach 2.0 ist die aktuelle Einwilligung erforderlich."},400);
    const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)return res({ok:false,code:"auth_required"},401);const db=admin(),user=(await db.auth.getUser(token)).data.user;if(!user)return res({ok:false,code:"auth_invalid"},401);
    const ctx=await context(db,user.id),fallback=rules(ctx),key=Deno.env.get("OPENAI_API_KEY");let insight=fallback,source="rules",model=null;
    if(key){const prompt=`Du bist der Fitnest Coach 2.0. Antworte ausschließlich als JSON mit {"level":"unknown|stable|moderate|low|attention","status":string,"summary":string,"actions":string[1..4],"metrics":object}. Werte Schlaf, Energie, Schritte, Wasser, Gewichtstrend und Trainingsbelastung gemeinsam aus. Jede Aussage ist nur ein Hinweis. Sperre niemals Training, Planerstellung oder andere Funktionen. Verändere keine Pläne und Kalorienziele automatisch. Keine Diagnose. Keine Crash Diät. Fördere nie schnelleres Abnehmen als 1 kg pro Woche. Bei niedriger Erholung zuerst eine freiwillige leichtere Belastung vorschlagen. Sei knapp, konkret und deutsch.\n\nDaten: ${JSON.stringify(ctx)}`,response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6",store:false,input:prompt})});if(response.ok){try{const parsed=cleanJson(extractText(await response.json()));if(parsed?.status&&Array.isArray(parsed?.actions)){insight=safeInsight(parsed,fallback);source="ai";model="gpt-5.6"}}catch(error){console.warn("coach parse fallback",error)}}else console.warn("OpenAI coach",response.status,await response.text())}
    await db.from("coach_insights").insert({user_id:user.id,insight_date:new Date().toISOString().slice(0,10),source,analysis:insight,model});return res({ok:true,source,insight,consentVersion:CONSENT_VERSION});
  }catch(error:any){console.error("coach-analysis",error);return res({ok:false,code:"coach_error",message:String(error?.message||error)},500)}
});
