import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.95.0";

const ORIGIN="https://fitnest.reflectace.workers.dev";
const H={"Content-Type":"application/json","Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function res(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:H})}
function admin(){const m=Deno.env.get("SUPABASE_SECRET_KEYS"),key=m?JSON.parse(m).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!key)throw new Error("server_key_missing");return createClient(Deno.env.get("SUPABASE_URL")!,key,{auth:{persistSession:false,autoRefreshToken:false}})}
function avg(a:number[]){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function daysAgo(n:number){return new Date(Date.now()-n*86400000).toISOString().slice(0,10)}
function rules(ctx:any){const weights=(ctx.weights||[]).slice().reverse(),wchange=weights.length>1?Number(weights[0].weight_kg)-Number(weights.at(-1).weight_kg):null,workouts=ctx.workouts||[],rpes=workouts.map((x:any)=>Number(x.perceived_effort)).filter(Boolean),steps=(ctx.checkins||[]).map((x:any)=>Number(x.steps||0)),meals=new Set((ctx.meals||[]).map((x:any)=>x.eaten_on)).size,p=ctx.profile||{},np=ctx.nutrition||{};let status="Stabil weitermachen",summary="Deine Daten sprechen für eine konservative Fortsetzung ohne unnötige Verschärfung.",actions:string[]=[];const ar=avg(rpes);if(ar>=8.5){status="Belastung runter";summary="Die jüngsten Trainings waren sehr fordernd.";actions.push("Heute keine zusätzliche Trainingsprogression erzwingen.")}else if(workouts.length>=Math.max(2,Number(p.training_days||3))&&ar>0&&ar<=6.5){status="Progression möglich";summary="Trainingshäufigkeit und Belastung lassen eine kleine Progression zu.";actions.push("Nur bei sauberer Technik moderat steigern.")}else actions.push("Geplanten Trainingsrhythmus beibehalten.");const st=avg(steps);if(st&&p.step_goal&&st<Number(p.step_goal)*.75)actions.push("Zuerst Alltagsbewegung stabilisieren, bevor Ernährung weiter verschärft wird.");if(np.eating_pattern==="omad")actions.push("1MAD nur als Essensrhythmus behandeln: Tagesenergie, Protein und Nährstoffdichte vollständig abdecken.");if(meals<3)actions.push("Mehrere Ernährungstage protokollieren, damit Empfehlungen belastbarer werden.");return{status,summary,actions:actions.slice(0,4),metrics:{workouts7:workouts.length,avgRpe:ar?Number(ar.toFixed(1)):null,avgSteps:st?Math.round(st):0,mealDays:meals,weightChange14:wchange!=null?Number(wchange.toFixed(1)):null,pattern:np.eating_pattern||"regular"}}}
async function context(db:any,userId:string){const [profile,goal,weights,workouts,checkins,meals,nutrition,review]=await Promise.all([db.from("profiles").select("age,height_cm,activity_level,training_days,session_minutes,step_goal,water_goal_l").eq("user_id",userId).maybeSingle(),db.from("goals").select("start_weight_kg,target_weight_kg,target_date,status").eq("user_id",userId).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle(),db.from("body_metrics").select("measured_on,weight_kg").eq("user_id",userId).gte("measured_on",daysAgo(30)).order("measured_on",{ascending:false}),db.from("workout_sessions").select("planned_date,duration_minutes,perceived_effort,workout_type").eq("user_id",userId).eq("completed",true).gte("planned_date",daysAgo(7)).order("planned_date",{ascending:false}),db.from("daily_checkins").select("checkin_date,steps,water_l,sleep_hours,energy").eq("user_id",userId).gte("checkin_date",daysAgo(7)).order("checkin_date",{ascending:false}),db.from("meal_logs").select("eaten_on,calories,protein_g,estimated_cost_eur").eq("user_id",userId).gte("eaten_on",daysAgo(7)),db.from("nutrition_profiles").select("name,diet_style,calories,protein_g,eating_pattern,meals_per_day,meal_schedule,budget_amount,budget_period").eq("user_id",userId).eq("is_active",true).maybeSingle(),db.from("weekly_reviews").select("metrics,recommendation,status,week_start").eq("user_id",userId).order("week_start",{ascending:false}).limit(1).maybeSingle()]);return{profile:profile.data,goal:goal.data,weights:weights.data||[],workouts:workouts.data||[],checkins:checkins.data||[],meals:meals.data||[],nutrition:nutrition.data,weeklyReview:review.data}}
function extractText(j:any){return j?.output?.flatMap((x:any)=>x?.content||[]).find((x:any)=>x?.type==="output_text")?.text||""}
function cleanJson(t:string){const s=t.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").trim();return JSON.parse(s)}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return res({ok:false,code:"method_not_allowed"},405);try{const body=await req.json().catch(()=>({}));if(body.consent!==true)return res({ok:false,code:"consent_required"},400);const token=req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token)return res({ok:false,code:"auth_required"},401);const db=admin(),u=(await db.auth.getUser(token)).data.user;if(!u)return res({ok:false,code:"auth_invalid"},401);const ctx=await context(db,u.id),fallback=rules(ctx),key=Deno.env.get("OPENAI_API_KEY");let insight=fallback,source="rules",model=null;if(key){const prompt=`Du bist der Fitnest Coach. Antworte ausschließlich als JSON mit {"status":string,"summary":string,"actions":string[1..4],"metrics":object}. Nutze die gelieferten realen Verlaufsdaten. Keine Diagnose. Keine Crash-Diät. Nie schnelleres Abnehmen als 1 kg/Woche fördern. Kalorien nicht automatisch weiter senken. Ein 1MAD/OMAD-Profil ist nur ein Nutzer-Rhythmus, keine Empfehlung und kein Grund für ein größeres Defizit. Bei hoher RPE zuerst Belastung reduzieren. Sei knapp, konkret und deutsch.\n\nDaten: ${JSON.stringify(ctx)}`;const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6",store:false,input:prompt})});if(r.ok){const j=await r.json();try{const x=cleanJson(extractText(j));if(x?.status&&Array.isArray(x?.actions)){insight={...fallback,...x,metrics:{...fallback.metrics,...(x.metrics||{})}};source="ai";model="gpt-5.6"}}catch(e){console.warn("coach parse fallback",e)}}else console.warn("OpenAI coach",r.status,await r.text())}await db.from("coach_insights").insert({user_id:u.id,insight_date:new Date().toISOString().slice(0,10),source,analysis:insight,model});return res({ok:true,source,insight})}catch(e:any){console.error("coach-analysis",e);return res({ok:false,code:"coach_error",message:String(e?.message||e)},500)}});
